name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: ./dev/up
      - run: cd remote-attachment ; npm install
      - run: cd remote-attachment ; NODE_TLS_REJECT_UNAUTHORIZED=0 npm test
