name: No code changes

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - ".changeset/config.json"
      - ".github/**"
      - "!.github/workflows/js-sdk.yml"
      - "!.github/workflows/mls-client.yml"
      - ".vscode/**"
      - ".yarn/**"
      - "*"
      - "!.node-version"
      - "!.nvmrc"
      - "!.prettierignore"
      - "!.prettierrc.cjs"
      - "!.yarnrc.yml"
      - "!turbo.json"
      - "!yarn.lock"

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to typecheck"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to lint"

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Format check
        run: yarn prettier -c .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to test"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to build"
