name: No code changes

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - ".changeset/config.json"
      - ".github/**"
      - "!.github/workflows/js-sdk.yml"
      - "!.github/workflows/mls-client.yml"
      - "!.github/workflows/content-types.yml"
      - ".vscode/**"
      - ".yarn/**"
      - "*"
      - "!.node-version"
      - "!.nvmrc"
      - "!.prettierignore"
      - "!.prettierrc.cjs"
      - "!.yarnrc.yml"
      - "!turbo.json"
      - "!yarn.lock"

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to typecheck"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to lint"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to test"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to build"
